version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - efk

  fluentd:
    image: fluent/fluentd:edge
    container_name: fluentd
    volumes:
      - ./fluentd:/fluentd/etc
    links:
      - elasticsearch
    networks:
      - efk
    ports:
      - "24224:24224"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - efk
networks:
  efk:
